apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: trainingservice
  name: trainingservice
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8088
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: trainingservice
status:
  loadBalancer: { }